#                                                                         
/control/verbose 2
/run/verbose 1
#Set up geometry
/alpha/det/setTargetShape Box
/alpha/det/setTargetMaterial PEN 
/alpha/det/setTargetHalfX 10 cm
/alpha/det/setTargetHalfY 10 cm
/alpha/det/setTargetHalfZ 75 um
#
/run/numberOfThreads 16

/run/initialize
/process/had/rdm/nucleusLimits 231 233 89 91
/process/had/rdm/thresholdForVeryLongDecayTime 1e20 y

/generator/setPositionMode InBulk
/generator/setDepthInTarget 75 um
#/generator/setPositionMode Point
#/generator/setPositionX 0
#/generator/setPositionY 0
#/generator/setPositionZ 1 cm
/gun/particle ion
/gun/ion 90 232

/run/fileName run232Th_bulk.root
/run/printProgress 100000
/run/beamOn 10000000


/process/had/rdm/nucleusLimits 227 229 89 91
/gun/particle ion
/gun/ion 90 228

/run/fileName run228Th_bulk.root
/run/beamOn 10000000


/process/had/rdm/nucleusLimits 223 225 87 89
/gun/particle ion
/gun/ion 88 224

/run/fileName run224Ra_bulk.root
/run/beamOn 10000000


/process/had/rdm/nucleusLimits 219 221 85 87
/gun/particle ion
/gun/ion 86 220

/run/fileName run220Rn_bulk.root
/run/beamOn 10000000


/process/had/rdm/nucleusLimits 215 217 83 85
/gun/particle ion
/gun/ion 84 216

/run/fileName run216Po_bulk.root
/run/beamOn 10000000


/process/had/rdm/nucleusLimits 211 213 82 84
/gun/particle ion
/gun/ion 83 212

/run/fileName run212Bi_bulk.root
/run/beamOn 3594000


/process/had/rdm/nucleusLimits 211 213 83 85
/gun/particle ion
/gun/ion 84 212

/run/fileName run212Po_bulk.root
/run/beamOn 6406000

