#                                                                         
/control/verbose 2
/run/verbose 1
#
/run/numberOfThreads 4

/run/initialize
/process/had/rdm/nucleusLimits 240 242 94 96

/generator/setPositionMode OnSurface
#/generator/setPositionMode Point
#/generator/setPositionX 0
#/generator/setPositionY 0
#/generator/setPositionZ 1 cm
/gun/particle ion
/gun/ion 95 241

/run/fileName run241Am.root
/run/beamOn 10000

